from rdflib import Graph, Literal, Namespace, RDF, URIRef, BNode

graph = Graph()
rdfs = Namespace('http://www.w3.org/2000/01/rdf-schema#')
rdf = Namespace('http://www.w3.org/1999/02/22-rdf-syntax-ns#')
schema = Namespace('https://schema.org/')
eaccpf = Namespace('http://culturalis.org/eac-cpf#')
dbo = Namespace('http://dbpedia.org/ontology/')
djo = Namespace('http://dijest.ac.il/ontology/')
djr = Namespace('http://dijest.ac.il/resource/')
owl = Namespace('http://www.w3.org/2002/07/owl#')
fabio = Namespace('http://purl.org/spar/fabio/')
eaccpf = Namespace('http://culturalis.org/eac-cpf#')
owl = Namespace('http://www.w3.org/2002/07/owl#')
bf = Namespace('http://id.loc.gov/ontologies/bibframe/')
gnd = Namespace('https://d-nb.info/standards/elementset/gnd#')
gn = Namespace('https://www.geonames.org/ontology#')


graph.bind('rdfs', rdfs)
graph.bind('rdf', rdf)
graph.bind('schema', schema)
graph.bind('eac-cpf', eaccpf)
graph.bind('dbo', dbo)
graph.bind('djo', djo)
graph.bind('owl', owl)
graph.bind('fabio', fabio)
graph.bind('eac-cpf', eaccpf)
graph.bind('bf', bf)
graph.bind('gnd', gnd)
graph.bind('gn', gn)

graph.add((djo['Place'], RDF['type'], owl['Class']))
graph.add((djo['Place'], rdfs['label'], Literal('Place')))
graph.add((djo['Place'], rdfs['subClassOf'], owl['Thing']))
graph.add((djo['Place'], owl['equivalentClass'], schema['Place']))
graph.add((djo['Place'], owl['equivalentClass'], gn['Feature']))

graph.add((djo['Book'], RDF['type'], owl['Class']))
graph.add((djo['Book'], rdfs['label'], Literal('Book')))
graph.add((djo['Book'], rdfs['subClassOf'], owl['Thing']))
graph.add((djo['Book'], owl['equivalentClass'], schema['Book']))
graph.add((djo['Book'], owl['equivalentClass'], fabio['Book']))
graph.add((djo['Book'], owl['equivalentClass'], bf['Work']))
graph.add((djo['Book'], owl['equivalentClass'], gnd['Work']))

graph.add((djo['Person'], RDF['type'], owl['Class']))
graph.add((djo['Person'], rdfs['label'], Literal('Person')))
graph.add((djo['Person'], rdfs['subClassOf'], owl['Thing']))
graph.add((djo['Person'], owl['equivalentClass'], schema['Person']))
graph.add((djo['Person'], owl['equivalentClass'], dbo['Person']))
graph.add((djo['Person'], owl['equivalentClass'], eaccpf['Person']))



graph.serialize(destination='ontology.ttl',format='turtle', encoding='utf8') 
